# GitHub Pages Configuration
name: Maple Yarns

# SEO and metadata
title: "Maple Yarns - Stella & Maple's Crochet Adventures"
description: "Join Stella and her orange cat Maple on their adorable crochet adventures! Sweet patterns, cozy crafts, and purr-fect creations."
author: "Stella & Maple"
url: "https://mapleyarns.com"
baseurl: ""

# Social links
social:
  name: Stella & Maple
  links:
    - https://instagram.com/mapleyarns
instagram_username: mapleyarns
pinterest_username: mapleyarns
etsy_shop: mapleyarns

# SEO specific settings
logo: /assets/images/maple-logo.png
twitter:
  username: mapleyarns
  card: summary_large_image

# Language and locale
lang: en_US
timezone: America/New_York

# Build settings for static site
exclude:
  - README.md
  - package.json
  - node_modules/
  - .gitignore
  - .vscode/
  - SEO-CHECKLIST.md
