# GitHub Pages Configuration
name: Maple Yarns

# Jekyll configuration (optional - GitHub Pages can serve static HTML)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO and metadata
title: "Maple Yarns - Stella & Maple's Crochet Adventures"
description: "Join Stella and her orange cat Maple on their adorable crochet adventures! Sweet patterns, cozy crafts, and purr-fect creations."
author: "Stella & Maple"
url: "https://mapleyarns.com" # Changed from https://fgrandi.github.io
baseurl: "" # Changed from /Maple-Yarns

# Social links (update with your information)
instagram_username: mapleyarns
pinterest_username: mapleyarns
etsy_shop: mapleyarns

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - package.json
  - node_modules/
  - .gitignore
  - .vscode/
  - test.css
  - styles/main-clean.css
  - styles/main.css.backup
  - styles/minimal.css
